### ISSUE TITLE
v1.0.13 still get RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. 

### ISSUE THREAD

**Issue by isikhi** [amqp/rhea#269]
I updated rhea but still i get this error. The range still wont satisfied. How would i handle it? 
```

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 259
   at writeU_Int8 (internal/buffer.js:561:11)
   at Buffer.writeUInt8 (internal/buffer.js:571:10)
   at types.Writer.write_uint (/filepath/node_modules/rhea/lib/types.js:726:28)
   at types.Writer.write_variable_width (/filepath/node_modules/rhea/lib/types.js:752:10)
   at types.Writer.write_value (/filepath/node_modules/rhea/
....
```

**Comment by grs** [comment]
Can you create a reproducer?
