### ISSUE TITLE
Get TypeError: this.options.reconnect is not a function when connection is disconnected

### ISSUE THREAD

**Issue by RishabhKarnad** [amqp/rhea#294]
Hi. I have been receiving the following error from my AMQP broker:

```
[ConnectionError: local-idle-timeout expired] {
  message: 'local-idle-timeout expired',
  name: 'ConnectionError',
  condition: 'amqp:resource-limit-exceeded',
  description: 'local-idle-timeout expired',
  connection: <ref *1> Connection {
    options: {
      id: [REDACTED],
      host: [REDACTED],
      port: '15672',
      username: [REDACTED],
      password: [REDACTED],
      idle_time_out: 2147483647,
      reconnect: [Object],
      container_id: [REDACTED],
      connection_details: [Function (anonymous)]
    },
    container: Container {
      options: {},
      id: [REDACTED],
      sasl_server_mechanisms: {}
    },
    registered: false,
    state: EndpointState {
      local_open: true,
      remote_open: false,
      open_requests: 0,
      close_requests: 0,
      initialised: true,
      marker: undefined
    },
    local_channel_map: { '0': [Session] },
    remote_channel_map: { '0': [Session] },
    local: { open: [c], close: [c] },
    remote: { open: [c], close: [c] },
    session_policy: { get_session: [Function: get_session] },
    amqp_transport: Transport {
      identifier: [REDACTED],
      protocol_id: 0,
      frame_type: 0,
      handler: [Circular *1],
      pending: [],
      header_sent: [Object],
      header_received: [Object],
      write_complete: false,
      read_complete: false
    },
    sasl_transport: SaslClient {
      connection: [Circular *1],
      transport: [Transport],
      next: [Transport],
      mechanisms: [Object],
      mechanism: [PlainClient],
      mechanism_name: 'PLAIN',
      hostname: [REDACTED],
      failed: false
    },
    transport: SaslClient {
      connection: [Circular *1],
      transport: [Transport],
      next: [Transport],
      mechanisms: [Object],
      mechanism: [PlainClient],
      mechanism_name: 'PLAIN',
      hostname: [REDACTED],
      failed: false
    },
    conn_established_counter: 1,
    heartbeat_out: Timeout {
      _idleTimeout: 4000,
      _idlePrev: [TimersList],
      _idleNext: [TimersList],
      _idleStart: 67488,
      _onTimeout: [Function: bound ],
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: false,
      [Symbol(refed)]: true,
      [Symbol(asyncId)]: 475,
      [Symbol(triggerId)]: 432
    },
    heartbeat_in: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 16853,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(asyncId)]: 164,
      [Symbol(triggerId)]: 104
    },
    abort_idle: false,
    socket_ready: true,
    scheduled_reconnect: undefined,
    default_sender: undefined,
    closed_with_non_fatal_error: false,
    is_server: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: [Object],
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      _peername: [Object],
      [Symbol(asyncId)]: 104,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: true,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _events: [Object: null prototype] {
      connection_open: [Function (anonymous)],
      connection_error: [Function (anonymous)],
      connection_close: [Function (anonymous)]
    },
    _eventsCount: 3
  }
}
```

In an attempt to allow the client to reconnect after the error, I tried adding the error condition 'amqp:resource-limit-exceeded' to `non_fatal_errors` in the connection options

```
// connection options

{
    id: ...,
    host,
    port,
    username,
    password,
    idle_time_out: 2147483647,
    reconnect: {
      max_reconnect_delay: 30000,
    },
    non_fatal_errors: [
      'amqp:resource-limit-exceeded',
    ],
  }
```

On receiving the error, I now see the following when the client presumably tries to reconnect:

```
TypeError: this.options.reconnect is not a function
     at Connection._disconnected (/home/ubuntu/.../server/node_modules/rhea/lib/connection.js:604:38)
     at Connection.on_error (/home/ubuntu/.../server/node_modules/rhea/lib/connection.js:574:10)
     at Socket.emit (events.js:315:20)
     at errorOrDestroy (internal/streams/destroy.js:128:12)
     at onwriteError (_stream_writable.js:406:3)
     at processTicksAndRejections (internal/process/task_queues.js:86:21)
```

Is there something wrong with my configuration, or could this be a bug?

Thanks!

**Comment by grs** [comment]
The max_reconnect_delay option should be a top level property on the connection options, not a property of reconnect. The reconnect can be a boolean (whether or not to use the inbuilt reconnect logic), a number (a fixed delay between reconnect attempts) or a function that returns the time to delay before reconnecting or a negative number if not to reconnect.

**Comment by RishabhKarnad** [comment]
Thanks for the quick reply @grs. I added the max_reconnect_delay option under reconnect, because the nesting appeared that way in the readme doc. I'm not able to reproduce the original issue that caused the disconnect anymore, so closing the issue for now.
