### ISSUE TITLE
Uncaught exception when doing a broker FailOver

### ISSUE THREAD

**Issue by touzaniMarouane** [amqp/rhea#306]
Hello,
I have this error when doing a failOver test on AmazonMQ, any Ideas ?
```
		"metadata": {
			"message": "Cannot call write after a stream was destroyed",
			"stack": "Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed\\n
                at doWrite (_stream_writable.js:399:19)\\n
                at writeOrBuffer (_stream_writable.js:387:5)\\n
                at Socket.Writable.write (_stream_writable.js:318:11)\\n
                at Function.log (/home/node/inst001/node_modules/debug/src/node.js:108:25)\\n
                at Object.debug [as events] (/home/node/inst001/node_modules/debug/src/common.js:115:13)\\n
                at Connection.dispatch (/home/node/inst001/node_modules/rhea/lib/connection.js:242:9)\\n
                at Connection.input (/home/node/inst001/node_modules/rhea/lib/connection.js:522:18)\\n
                at TLSSocket.emit (events.js:315:20)\\n
                at addChunk (_stream_readable.js:295:12)\\n
                at readableAddChunk (_stream_readable.js:271:9)\\n
                at TLSSocket.Readable.push (_stream_readable.js:212:10)\\n
                at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)",
			"code": "ERR_STREAM_DESTROYED"
		}
```

**Comment by grs** [comment]
I don't understand that stack trace. It looks as if the debug library is trying to write to a socket. Can you create a simple reproducer?

**Comment by touzaniMarouane** [comment]
@grs this happen when closing a receiver with DEBUG=rhea* on, disabling debug solved my problem.
